### ISSUE TITLE
This says bo's are better than Mc's

### ISSUE THREAD

**Issue by Skumar101** [HarryYu1/The-Rainbow#5]
Its obvious Mc's are better than bos but this says otherwise. Pls fix as quick as possible.

**Comment by HarryYu1** [comment]
ik sorry

**Comment by Skumar101** [comment]
> nah
im telling the manager of this establishment 😡😡

**Comment by HarryYu1** [comment]
> > nah
> > im telling the manager of this establishment 😡😡

https://genesismud.org/play
